name: Content Build and Deploy (Cloudflare Pages)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

env:
  # Template repo that publishes llog binary + skeleton
  TEMPLATE_REPO: limcpf/llog
  # Set repository variable LLOG_VERSION to pin (e.g., v0.1.0); otherwise 'latest'
  LLOG_VERSION: ${{ vars.LLOG_VERSION || 'latest' }}
  # Cloudflare Pages project name (set as repo variable CF_PAGES_PROJECT)
  CF_PAGES_PROJECT: ${{ vars.CF_PAGES_PROJECT }}
  # Path to your Obsidian vault root inside this repo ('.' for repo root)
  VAULT_DIR: ${{ vars.VAULT_DIR || '.' }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout content repo
        uses: actions/checkout@v4

      - name: Resolve llog version
        id: ver
        run: |
          if [ "${LLOG_VERSION}" = "latest" ]; then
            TAG=$(curl -fsSL https://api.github.com/repos/${TEMPLATE_REPO}/releases/latest \
              | grep -m1 '"tag_name"' \
              | sed -E 's/.*"tag_name"\s*:\s*"([^"]+)".*/\1/')
          else
            TAG="${LLOG_VERSION}"
          fi
          echo "tag=${TAG}" >> "$GITHUB_OUTPUT"

      - name: Download llog binary + skeleton
        run: |
          set -euo pipefail
          TAG="${{ steps.ver.outputs.tag }}"
          echo "Using llog release: $TAG"
          curl -fL -o llog "https://github.com/${TEMPLATE_REPO}/releases/download/${TAG}/llog-linux-amd64"
          curl -fL -o site-skeleton.tar.gz "https://github.com/${TEMPLATE_REPO}/releases/download/${TAG}/site-skeleton.tar.gz"
          chmod +x llog

      - name: Prepare working directory
        run: |
          set -euo pipefail
          rm -rf work dist
          mkdir -p work
          tar -xzf site-skeleton.tar.gz -C work
          # Optional: if repo provides overrides/ or site.json, overlay them
          if [ -d overrides ]; then rsync -a overrides/ work/; fi
          if [ -f site.json ]; then cp -f site.json work/site.json; fi

      - name: Import Markdown and build
        run: |
          set -euo pipefail
          ./llog import:md --src "${VAULT_DIR}" --root work --verbose
          ./llog build --src work --out dist --verbose
          test -f dist/index.html

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ env.CF_PAGES_PROJECT }}
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

